[package]
name = "forge"
version = "0.1.1"
edition = "2021"
description = "competitive programming exercise scaffolder with a c++ template system"
license = "MIT"
repository = "https://github.com/afonp/forge"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2"
dirs = "5"
git2 = { version = "0.19", features = ["vendored-openssl"] }
chrono = "0.4"
